import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@components/styles/Home.module.css'
import React from 'react';
import Nav from '@components/components/Nav/Nav';
// import styles from '../styles/VideoListPage.module.css';

const inter = Inter({ subsets: ['latin'] })

  const videos = [
    {
      id: 1,
      title: 'Video 1',
      thumbnail: 'https://via.placeholder.com/300x200.png',
    },
    {
      id: 2,
      title: 'Video 2',
      thumbnail: 'https://via.placeholder.com/300x200.png',
    },
    {
      id: 3,
      title: 'Video 3',
      thumbnail: 'https://via.placeholder.com/300x200.png',
    },
    {
      id: 4,
      title: 'Video 4',
      thumbnail: 'https://via.placeholder.com/300x200.png',
    },
    {
      id: 5,
      title: 'Video 5',
      thumbnail: 'https://via.placeholder.com/300x200.png',
    },
    {
      id: 6,
      title: 'Video 6',
      thumbnail: 'https://via.placeholder.com/300x200.png',
    },
    {
      id: 7,
      title: 'Video 7',
      thumbnail: 'https://via.placeholder.com/300x200.png',
    },
    {
      id: 8,
      title: 'Video 8',
      thumbnail: 'https://via.placeholder.com/300x200.png',
    },
  ];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
      <Nav />
      <div className={styles.videoList}>
        {videos.map((video) => (
          <div className={styles.videoCard} key={video.id}>
            <img src={video.thumbnail} alt={video.title} />
            <h3>{video.title}</h3>
          </div>
        ))}
      </div>
    </div>
    </>
  )
}


// const VideoListPage = () => {
//   const videos = [
//     {
//       id: 1,
//       title: 'Video 1',
//       thumbnail: 'https://via.placeholder.com/300x200.png',
//     },
//     {
//       id: 2,
//       title: 'Video 2',
//       thumbnail: 'https://via.placeholder.com/300x200.png',
//     },
//     {
//       id: 3,
//       title: 'Video 3',
//       thumbnail: 'https://via.placeholder.com/300x200.png',
//     },
//     {
//       id: 4,
//       title: 'Video 4',
//       thumbnail: 'https://via.placeholder.com/300x200.png',
//     },
//     {
//       id: 5,
//       title: 'Video 5',
//       thumbnail: 'https://via.placeholder.com/300x200.png',
//     },
//     {
//       id: 6,
//       title: 'Video 6',
//       thumbnail: 'https://via.placeholder.com/300x200.png',
//     },
//     {
//       id: 7,
//       title: 'Video 7',
//       thumbnail: 'https://via.placeholder.com/300x200.png',
//     },
//     {
//       id: 8,
//       title: 'Video 8',
//       thumbnail: 'https://via.placeholder.com/300x200.png',
//     },
//   ];

//   return (
   
//   );
// };

// export default VideoListPage;
